Dockerfile  form.html  main.py  pod.yaml  requirements.txt
ubuntu@ip-172-31-16-125:~/devfolder$ vi pod.yaml
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc1
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 8089
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer-pod1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: pramothar/kube30:latest
          imagePullPolicy: Always

